[package]
name = "stock_data"
version = "0.1.0"
authors = ["sintaro <sintaronettt@gmail.com>"]
edition = "2018"

[dependencies]
lambda_runtime = "0.4"
lambda_http = "0.4.0"
serde_json = "1.0.59"
tokio = "1.11.0"
reqwest = "0.11.9"

[[bin]]
name = "docker-lambda-rust-builder"
path = "src/main.rs"
